env:
  browser: true
  es2021: true
extends:
  - airbnb
  - airbnb-typescript
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project: "03-CurrencyConverter/converter/tsconfig.json"
  sourceType: "module"
plugins:
  - '@typescript-eslint'
  - react
rules:
  react/jsx-filename-extension:
    - 1
    - extensions: [".tsx", ".ts"]
  filesWithoutExtension: 0
  react/react-in-jsx-scope: 0